# Generated by Django 4.2.4 on 2024-04-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact',
            new_name='country',
        ),
    ]
